# Generated by Django 3.2.4 on 2021-06-04 10:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Максимальная длина 255 символов', max_length=255, unique=True, verbose_name='Дилерский центр')),
                ('profit', models.IntegerField(default=0, verbose_name='Прибыль')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Максимальная длина 100 символов', max_length=100, verbose_name='Марка')),
                ('model', models.CharField(help_text='Максимальная длина 100 символов', max_length=100, verbose_name='Модель автомобиля')),
                ('color', models.CharField(help_text='Максимальная длина 25 символов', max_length=25, verbose_name='Цвет автомобиля')),
                ('vin', models.CharField(db_index=True, help_text='Поле уникальное, максимальная длина 100 символов', max_length=100, unique=True, verbose_name='VIN номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата продажи заполняется автоматически', verbose_name='Дата продажи')),
                ('price', models.IntegerField(verbose_name='Цена захода')),
                ('profit', models.IntegerField(verbose_name='Чистая прибыль')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='dealers.dealership', verbose_name='Дилерский центр')),
            ],
            options={
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Максимальная длина 255 символов', max_length=255, unique=True, verbose_name='Название дилера')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Название детали, максимальная длина 250 символов', max_length=250, verbose_name='Название')),
                ('quantity', models.PositiveSmallIntegerField(help_text='Не может быть отрицательным', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='dealers.dealership', verbose_name='Дилерский центр')),
            ],
            options={
                'verbose_name_plural': 'Детали',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Максимальная длина 100 символов', max_length=100, verbose_name='Марка')),
                ('model', models.CharField(help_text='Максимальная длина 100 символов', max_length=100, verbose_name='Модель автомобиля')),
                ('color', models.CharField(help_text='Максимальная длина 25 символов', max_length=25, verbose_name='Цвет автомобиля')),
                ('vin', models.CharField(db_index=True, help_text='Поле уникальное, максимальная длина 100 символов', max_length=100, unique=True, verbose_name='VIN номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата поступления заполняется автоматически', verbose_name='Дата поступления')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость без наценки')),
                ('markup', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наценка в %')),
                ('cost', models.IntegerField(blank=True, verbose_name='Цена')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='dealers.dealership', verbose_name='Дилерский центр')),
            ],
            options={
                'verbose_name_plural': 'Атомобили',
                'ordering': ('-pub_date',),
            },
        ),
    ]
